icp:
  # ICP settings
  max_distance: 16
  max_iterations: 100
  transformation_epsilon: 0.01
  weight_mode: distance_inverse # choices: distance_inverse, distance_max_scaling, uniform
  reject_mode: none # choices: none, threshold, percentage
  reject_percentage: 0.1 # for icp pair rejection 
  reject_threshold: 5 # for icp pair rejection
  debug_mode: false # choices: true, false

  # Refernce cloud settings
  update_mode : map_mode  # choices: previous_frame, key_frame, map_mode

  # Key frame settings
  key_frame_mode : time_mode # choices: time_mode, overlap_mode
  time_threshold : 0.1 # only used for key frame mode (time)
  overlap_threshold: 0.98 # only used for key frame mode (overlap)

  # Map settings
  map_size : 10000 # amount of points in the map
  map_range : 55 # maximum distance from robot to map points
  remove_mode: euclidean_norm # choices: euclidean_norm, inf_norm
  