icp:
  # ICP settings
  max_distance: 5
  max_iterations: 100
  transformation_epsilon: 0.01
  weight_mode: distance_inverse # choices: distance_inverse, distance_max_scaling, uniform
  reject_mode: none # choices: none, threshold, percentage
  reject_percentage: 0.1
  debug_mode: false # choices: true, false

  # Refernce cloud settings
  update_mode : key_frame  # choices: previous_frame, key_frame, map_mode

  # Key frame settings
  key_frame_mode : overlap_mode # choices: time_mode, overlap_mode
  time_threshold : 0.001 # only used for key frame mode
  overlap_threshold: 0.99

  # Map settings
  map_size : 10000
  map_range : 55 
  remove_mode: euclidean_norm # choices: euclidean_norm, inf_norm
  